In [1]:
#Chargement des librairy
import numpy as np
import pandas as pd
#Chargement du ficher de travail
source = "HDR 2007-2008 Table 10.xlsx"
df = pd.read_excel(source)
#Afficher les 12 première lignes
df.head(12)

,Unnamed: 0,…to lead a long and healthy life…,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,10 Survival: progress and setbacks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MDG,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Life expectancy at birth\n(years),NaN,NaN,NaN,"Infant mortality rate\n(per 1,000 live births)",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HDI rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,1970-75d,NaN,2000-05d,NaN,1970,NaN,2005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,Iceland,NaN,74.3,NaN,81.0,NaN,13,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2,Norway,NaN,74.4,NaN,79.3,NaN,13,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3,Australia,NaN,71.7,NaN,80.4,NaN,17,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,4,Canada,NaN,73.2,NaN,79.8,NaN,19,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5,Ireland,NaN,71.3,NaN,77.8,NaN,20,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
# Repositionner la ligne d'en-tête en supprimant les espaces avant
df = pd.read_excel(source, header=3)
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,MDG,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,NaN,NaN,NaN,Life expectancy at birth\n(years),NaN,NaN,NaN,"Infant mortality rate\n(per 1,000 live births)",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HDI rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,1970-75d,NaN,2000-05d,NaN,1970,NaN,2005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Iceland,NaN,74.3,NaN,81.0,NaN,13,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2,Norway,NaN,74.4,NaN,79.3,NaN,13,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3,Australia,NaN,71.7,NaN,80.4,NaN,17,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,4,Canada,NaN,73.2,NaN,79.8,NaN,19,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5,Ireland,NaN,71.3,NaN,77.8,NaN,20,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,6,Sweden,NaN,74.7,NaN,80.1,NaN,11,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,7,Switzerland,NaN,73.8,NaN,80.7,NaN,15,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,8,Japan,NaN,73.3,NaN,81.9,NaN,14,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,9,Netherlands,NaN,74.0,NaN,78.7,NaN,13,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,10,France,NaN,72.4,NaN,79.6,NaN,18,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,11,Finland,NaN,70.7,NaN,78.4,NaN,13,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,12,United States,NaN,71.5,NaN,77.4,NaN,20,NaN,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,13,Spain,NaN,72.9,NaN,80.0,NaN,27,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,14,Denmark,NaN,73.6,NaN,77.3,NaN,14,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,15,Austria,NaN,70.6,NaN,78.9,NaN,26,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,16,United Kingdom,NaN,72.0,NaN,78.5,NaN,18,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,17,Belgium,NaN,71.6,NaN,78.2,NaN,21,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,18,Luxembourg,NaN,70.6,NaN,78.2,NaN,19,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,19,New Zealand,NaN,71.7,NaN,79.2,NaN,17,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,20,Italy,NaN,72.1,NaN,79.9,NaN,30,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,21,"Hong Kong, China (SAR)",NaN,72.0,NaN,81.5,NaN,..,NaN,..,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,22,Germany,NaN,71.0,NaN,78.7,NaN,22,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,23,Israel,NaN,71.6,NaN,79.7,NaN,24,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,24,Greece,NaN,72.3,NaN,78.3,NaN,38,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,25,Singapore,NaN,69.5,NaN,78.8,NaN,22,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,26,Korea (Republic of),NaN,62.6,NaN,77.0,NaN,43,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,Least developed countries,NaN,NaN,44.6,h,52.7,h,152,h,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,Arab States,NaN,NaN,51.9,NaN,66.7,NaN,129,NaN,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,East Asia and the Pacific,NaN,NaN,60.6,NaN,71.1,NaN,84,NaN,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,Latin America and the Caribbean,NaN,NaN,61.2,NaN,72.2,NaN,86,NaN,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,South Asia,NaN,NaN,50.3,NaN,62.9,NaN,130,NaN,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,Sub-Saharan Africa,NaN,NaN,46.0,NaN,49.1,NaN,144,NaN,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,Central and Eastern Europe and the CIS,NaN,NaN,68.7,NaN,68.2,NaN,39,NaN,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,OECD,NaN,NaN,70.3,NaN,77.8,NaN,41,NaN,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,High-income OECD,NaN,NaN,71.7,NaN,78.9,NaN,22,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,High human development,NaN,NaN,69.4,NaN,75.7,NaN,43,NaN,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,Medium human development,NaN,NaN,56.6,NaN,66.9,NaN,106,NaN,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,Low human development,NaN,NaN,43.7,NaN,47.9,NaN,155,NaN,108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,High income,NaN,NaN,71.5,NaN,78.7,NaN,24,NaN,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,Middle income,NaN,NaN,61.8,NaN,70.3,NaN,87,NaN,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,Low income,NaN,NaN,49.1,NaN,59.2,NaN,130,NaN,75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,World,NaN,NaN,58.3,h,66.0,h,96,h,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,a. Data refer to the probability at birth of s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,"SOURCES\nColumns 1, 2, 7 and 8: UN 2007e.\nCol...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Délimiter le fichier
# Supprimez d'abord toutes les colonnes (axe=1) sans valeurs
df = df.dropna(how="all", axis=1)
# Supprimer toutes les lignes (axe=0) sans valeurs
df = df.dropna(how="all", axis=0).reset_index(drop=True)
df.head(6)

,Unnamed: 0,Unnamed: 1,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,MDG,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,MDG.2
0,NaN,NaN,Life expectancy at birth\n(years),NaN,NaN,NaN,"Infant mortality rate\n(per 1,000 live births)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Maternal mortality ratio\n (per 100,000 live b...",NaN,NaN
1,HDI rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Probability at birth of surviving to age 65a ...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,1970-75d,NaN,2000-05d,NaN,1970,NaN,2005,NaN,...,NaN,2005,NaN,Female\n2000-05d,NaN,Male\n2000-05d,NaN,Reportedb\n1990-2005e,NaN,Adjustedc\n2005
3,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Iceland,74.3,NaN,81.0,NaN,13,NaN,2,NaN,...,NaN,3,NaN,92.4,NaN,88.7,NaN,..,NaN,4
5,2,Norway,74.4,NaN,79.3,NaN,13,NaN,3,NaN,...,NaN,4,NaN,91.7,NaN,85.1,NaN,6,NaN,7

In [4]:
#lister des informations qui sont déjà là et utilisons cela pour guider les nouveaux noms que nous devons inclure.
columns = []
for c in df.columns:
    # Pour chaque colonne, obtenir les valeurs des 3 premières lignes
    # puis conservez toutes les chaînes (c'est-à-dire excluez-les si elles sont nulles) et ajoutez-les en colonne
    # A partir de High humain dev fusionner les colonnes ou les champs sont non vides
    columns.append([str(v) for v in df[c][:3] if pd.notnull(v)])
columns

[['HDI rank'],
 [],
 ['Life expectancy at birth\n(years)', '1970-75d'],
 [],
 ['2000-05d'],
 [],
 ['Infant mortality rate\n(per 1,000 live births)', '1970'],
 [],
 ['2005'],
 [],
 ['Under-five mortality rate\n(per 1,000 live births)', '1970'],
 [],
 ['2005'],
 [],
 ['Probability at birth of surviving to age 65a           (% of cohort)',
  'Female\n2000-05d'],
 [],
 ['Male\n2000-05d'],
 [],
 ['Maternal mortality ratio\n (per 100,000 live births)      ',
  'Reportedb\n1990-2005e '],
 [],
 ['Adjustedc\n2005']]

In [5]:
#Affecter des nouvelles entêtes aux colomns plus précises et pour les columns sans entêtes mettre reference x
columns = [
    "HDI rank",
    "Country",
    "Life expectancy at birth(years) 1970-1975d",
    "Reference 1",
    "Life expectancy at birth(years) 2000-2005d",
    "Reference 2",
    "Infant mortality rate(per 1,000 live births) 1970",
    "Reference 3",
    "Infant mortality rate(per 1,000 live births) 2005",
    "Reference 4",
    "Under-five mortality rate(per 1,000 live births) 1970",
    "Reference 5",
    "Under-five mortality rate(per 1,000 live births) 2005",
    "Reference 6",
    "Probability at birth of not surviving to age 65a (% of cohort) Female 2000-2005d",
    "Reference 7",
    "Probability at birth of not surviving to age 65a (% of cohort) Male 2000-2005d",   
    "Reference 8",
    "Maternal mortality ratio\n (per 100,000 live births) Reportedb 1990-2005e",   
    "Reference 9",
    "Maternal mortality ratio\n (per 100,000 live births) Adjustedc 2005"
]
df

,Unnamed: 0,Unnamed: 1,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,MDG,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,MDG.2
0,NaN,NaN,Life expectancy at birth\n(years),NaN,NaN,NaN,"Infant mortality rate\n(per 1,000 live births)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Maternal mortality ratio\n (per 100,000 live b...",NaN,NaN
1,HDI rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Probability at birth of surviving to age 65a ...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,1970-75d,NaN,2000-05d,NaN,1970,NaN,2005,NaN,...,NaN,2005,NaN,Female\n2000-05d,NaN,Male\n2000-05d,NaN,Reportedb\n1990-2005e,NaN,Adjustedc\n2005
3,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Iceland,74.3,NaN,81.0,NaN,13,NaN,2,NaN,...,NaN,3,NaN,92.4,NaN,88.7,NaN,..,NaN,4
5,2,Norway,74.4,NaN,79.3,NaN,13,NaN,3,NaN,...,NaN,4,NaN,91.7,NaN,85.1,NaN,6,NaN,7
6,3,Australia,71.7,NaN,80.4,NaN,17,NaN,5,NaN,...,NaN,6,NaN,92.2,NaN,86.2,NaN,..,NaN,4
7,4,Canada,73.2,NaN,79.8,NaN,19,NaN,5,NaN,...,NaN,6,NaN,91.0,NaN,84.9,NaN,..,NaN,7
8,5,Ireland,71.3,NaN,77.8,NaN,20,NaN,5,NaN,...,NaN,6,NaN,90.0,NaN,83.2,NaN,6,NaN,1
9,6,Sweden,74.7,NaN,80.1,NaN,11,NaN,3,NaN,...,NaN,4,NaN,92.3,NaN,87.0,NaN,5,NaN,3
10,7,Switzerland,73.8,NaN,80.7,NaN,15,NaN,4,NaN,...,NaN,5,NaN,92.6,NaN,86.1,NaN,5,NaN,5
11,8,Japan,73.3,NaN,81.9,NaN,14,NaN,3,NaN,...,NaN,4,NaN,93.8,NaN,86.1,NaN,8,NaN,6
12,9,Netherlands,74.0,NaN,78.7,NaN,13,NaN,4,NaN,...,NaN,5,NaN,90.4,NaN,84.4,NaN,7,NaN,6
13,10,France,72.4,NaN,79.6,NaN,18,NaN,4,NaN,...,NaN,5,NaN,92.2,NaN,82.1,NaN,10,NaN,8
14,11,Finland,70.7,NaN,78.4,NaN,13,NaN,3,NaN,...,NaN,4,NaN,91.8,NaN,81.0,NaN,6,NaN,7
15,12,United States,71.5,NaN,77.4,NaN,20,NaN,6,NaN,...,NaN,7,NaN,87.0,NaN,79.4,NaN,8,NaN,11
16,13,Spain,72.9,NaN,80.0,NaN,27,NaN,4,NaN,...,NaN,5,NaN,93.5,NaN,83.9,NaN,6,NaN,4
17,14,Denmark,73.6,NaN,77.3,NaN,14,NaN,4,NaN,...,NaN,5,NaN,87.4,NaN,81.3,NaN,10,NaN,3
18,15,Austria,70.6,NaN,78.9,NaN,26,NaN,4,NaN,...,NaN,5,NaN,91.9,NaN,82.4,NaN,..,NaN,4
19,16,United Kingdom,72.0,NaN,78.5,NaN,18,NaN,5,NaN,...,NaN,6,NaN,89.6,NaN,83.7,NaN,7,NaN,8
20,17,Belgium,71.6,NaN,78.2,NaN,21,NaN,4,NaN,...,NaN,5,NaN,91.0,NaN,81.9,NaN,..,NaN,8
21,18,Luxembourg,70.6,NaN,78.2,NaN,19,NaN,4,NaN,...,NaN,5,NaN,90.8,NaN,82.4,NaN,0,NaN,12
22,19,New Zealand,71.7,NaN,79.2,NaN,17,NaN,5,NaN,...,NaN,6,NaN,90.0,NaN,84.9,NaN,15,NaN,9
23,20,Italy,72.1,NaN,79.9,NaN,30,NaN,4,NaN,...,NaN,4,NaN,92.5,NaN,84.6,NaN,7,NaN,3
24,21,"Hong Kong, China (SAR)",72.0,NaN,81.5,NaN,..,NaN,..,NaN,...,NaN,..,NaN,93.6,NaN,86.3,NaN,..,NaN,..
25,22,Germany,71.0,NaN,78.7,NaN,22,NaN,4,NaN,...,NaN,5,NaN,91.0,NaN,82.9,NaN,8,NaN,4
26,23,Israel,71.6,NaN,79.7,NaN,24,NaN,5,NaN,...,NaN,6,NaN,92.3,NaN,85.8,NaN,5,NaN,4
27,24,Greece,72.3,NaN,78.3,NaN,38,NaN,4,NaN,...,NaN,5,NaN,91.3,NaN,83.7,NaN,1,NaN,3
28,25,Singapore,69.5,NaN,78.8,NaN,22,NaN,3,NaN,...,NaN,3,NaN,90.8,NaN,84.4,NaN,6,NaN,14
29,26,Korea (Republic of),62.6,NaN,77.0,NaN,43,NaN,5,NaN,...,NaN,5,NaN,90.8,NaN,78.6,NaN,20,NaN,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,168,Congo (Democratic Republic of the),46.0,NaN,45.0,NaN,148,NaN,129,NaN,...,NaN,205,NaN,38.8,NaN,33.3,NaN,"1,300",NaN,"1,100"
174,169,Ethiopia,43.5,NaN,50.7,NaN,160,NaN,109,NaN,...,NaN,164,NaN,46.9,NaN,41.4,NaN,870,NaN,720
175,170,Chad,45.6,NaN,50.5,NaN,154,NaN,124,NaN,...,NaN,208,NaN,50.5,NaN,43.7,NaN,"1,100",NaN,"1,500"
176,171,Central African Republic,43.5,NaN,43.3,NaN,145,NaN,115,NaN,...,NaN,193,NaN,32.1,NaN,25.7,NaN,"1,100",NaN,980
177,172,Mozambique,40.3,NaN,44.0,NaN,168,NaN,100,NaN,...,NaN,145,NaN,35.3,NaN,29.2,NaN,410,NaN,520
178,173,Mali,40.0,NaN,51.8,NaN,225,NaN,120,NaN,...,NaN,218,NaN,54.1,NaN,44.3,NaN,580,NaN,970
179,174,Niger,40.5,NaN,54.5,NaN,197,NaN,150,NaN,...,NaN,256,NaN,54.4,NaN,56.8,NaN,590,NaN,"1,800"
180,175,Guinea-Bissau,36.5,NaN,45.5,NaN,..,NaN,124,NaN,...,NaN,200,NaN,40.9,NaN,34.2,NaN,910,NaN,"1,100"
181,176,Burkina Faso,43.6,NaN,50.7,NaN,166,NaN,96,NaN,...,NaN,191,NaN,54.5,NaN,44.0,NaN,480,NaN,700
182,177,Sierra Leone,35.4,NaN,41.0,NaN,206,NaN,165,NaN,...,NaN,282,NaN,37.6,NaN,30.4,NaN,"1,800",NaN,"2,100"
183,Developing countries,NaN,55.8,NaN,65.5,NaN,109,h,57,h,...,h,83,h,70.3,NaN,62.6,NaN,..,NaN,..
184,Least developed countries,NaN,44.6,h,52.7,h,152,h,97,h,...,h,153,h,49.9,h,44.3,h,..,NaN,..
185,Arab States,NaN,51.9,NaN,66.7,NaN,129,NaN,46,NaN,...,NaN,58,NaN,73.5,NaN,66.4,NaN,..,NaN,..
186,East Asia and the Pacific,NaN,60.6,NaN,71.1,NaN,84,NaN,25,NaN,...,NaN,31,NaN,79.6,NaN,71.8,NaN,..,NaN,..
187,Latin America and the Caribbean,NaN,61.2,NaN,72.2,NaN,86,NaN,26,NaN,...,NaN,31,NaN,80.8,NaN,69.3,NaN,..,NaN,..
188,South Asia,NaN,50.3,NaN,62.9,NaN,130,NaN,60,NaN,...,NaN,80,NaN,66.0,NaN,58.4,NaN,..,NaN,..
189,Sub-Saharan Africa,NaN,46.0,NaN,49.1,NaN,144,NaN,102,NaN,...,NaN,172,NaN,43.3,NaN,37.8,NaN,..,NaN,..
190,Central and Eastern Europe and the CIS,NaN,68.7,NaN,68.2,NaN,39,NaN,22,NaN,...,NaN,27,NaN,79.5,NaN,54.9,NaN,..,NaN,..
191,OECD,NaN,70.3,NaN,77.8,NaN,41,NaN,9,NaN,...,NaN,11,NaN,89.2,NaN,80.5,NaN,..,NaN,..
192,High-income OECD,NaN,71.7,NaN,78.9,NaN,22,NaN,5,NaN,...,NaN,6,NaN,90.3,NaN,82.4,NaN,..,NaN,..
193,High human development,NaN,69.4,NaN,75.7,NaN,43,NaN,13,NaN,...,NaN,15,NaN,86.6,NaN,74.8,NaN,..,NaN,..
194,Medium human development,NaN,56.6,NaN,66.9,NaN,106,NaN,45,NaN,...,NaN,59,NaN,72.6,NaN,64.5,NaN,..,NaN,..
195,Low human development,NaN,43.7,NaN,47.9,NaN,155,NaN,108,NaN,...,NaN,184,NaN,42.6,NaN,37.4,NaN,..,NaN,..
196,High income,NaN,71.5,NaN,78.7,NaN,24,NaN,6,NaN,...,NaN,7,NaN,90.2,NaN,82.2,NaN,..,NaN,..
197,Middle income,NaN,61.8,NaN,70.3,NaN,87,NaN,28,NaN,...,NaN,35,NaN,78.9,NaN,68.4,NaN,..,NaN,..
198,Low income,NaN,49.1,NaN,59.2,NaN,130,NaN,75,NaN,...,NaN,113,NaN,60.0,NaN,53.2,NaN,..,NaN,..
199,World,NaN,58.3,h,66.0,h,96,h,52,h,...,h,76,h,72.0,h,63.1,h,..,NaN,..
200,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,a. Data refer to the probability at birth of s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,"SOURCES\nColumns 1, 2, 7 and 8: UN 2007e.\nCol...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Réinitialiser les colonnes du jeu de données
df.columns = columns
df.head()

,HDI rank,Country,Life expectancy at birth(years) 1970-1975d,Reference 1,Life expectancy at birth(years) 2000-2005d,Reference 2,"Infant mortality rate(per 1,000 live births) 1970",Reference 3,"Infant mortality rate(per 1,000 live births) 2005",Reference 4,...,Reference 5,"Under-five mortality rate(per 1,000 live births) 2005",Reference 6,Probability at birth of not surviving to age 65a (% of cohort) Female 2000-2005d,Reference 7,Probability at birth of not surviving to age 65a (% of cohort) Male 2000-2005d,Reference 8,"Maternal mortality ratio (per 100,000 live births) Reportedb 1990-2005e",Reference 9,"Maternal mortality ratio (per 100,000 live births) Adjustedc 2005"
0,NaN,NaN,Life expectancy at birth\n(years),NaN,NaN,NaN,"Infant mortality rate\n(per 1,000 live births)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Maternal mortality ratio\n (per 100,000 live b...",NaN,NaN
1,HDI rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Probability at birth of surviving to age 65a ...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,1970-75d,NaN,2000-05d,NaN,1970,NaN,2005,NaN,...,NaN,2005,NaN,Female\n2000-05d,NaN,Male\n2000-05d,NaN,Reportedb\n1990-2005e,NaN,Adjustedc\n2005
3,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Iceland,74.3,NaN,81.0,NaN,13,NaN,2,NaN,...,NaN,3,NaN,92.4,NaN,88.7,NaN,..,NaN,4

In [7]:
# Supprimer les lignes qui contenaient les informations dont nous n'avons plus besoin
# et réinitialiser l'index
# np.arange(3) crée un tableau = [0, 1, 2, 3]
df = df.drop(np.arange(3), axis=0).reset_index(drop=True)
df

,HDI rank,Country,Life expectancy at birth(years) 1970-1975d,Reference 1,Life expectancy at birth(years) 2000-2005d,Reference 2,"Infant mortality rate(per 1,000 live births) 1970",Reference 3,"Infant mortality rate(per 1,000 live births) 2005",Reference 4,...,Reference 5,"Under-five mortality rate(per 1,000 live births) 2005",Reference 6,Probability at birth of not surviving to age 65a (% of cohort) Female 2000-2005d,Reference 7,Probability at birth of not surviving to age 65a (% of cohort) Male 2000-2005d,Reference 8,"Maternal mortality ratio (per 100,000 live births) Reportedb 1990-2005e",Reference 9,"Maternal mortality ratio (per 100,000 live births) Adjustedc 2005"
0,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Iceland,74.3,NaN,81.0,NaN,13,NaN,2,NaN,...,NaN,3,NaN,92.4,NaN,88.7,NaN,..,NaN,4
2,2,Norway,74.4,NaN,79.3,NaN,13,NaN,3,NaN,...,NaN,4,NaN,91.7,NaN,85.1,NaN,6,NaN,7
3,3,Australia,71.7,NaN,80.4,NaN,17,NaN,5,NaN,...,NaN,6,NaN,92.2,NaN,86.2,NaN,..,NaN,4
4,4,Canada,73.2,NaN,79.8,NaN,19,NaN,5,NaN,...,NaN,6,NaN,91.0,NaN,84.9,NaN,..,NaN,7
5,5,Ireland,71.3,NaN,77.8,NaN,20,NaN,5,NaN,...,NaN,6,NaN,90.0,NaN,83.2,NaN,6,NaN,1
6,6,Sweden,74.7,NaN,80.1,NaN,11,NaN,3,NaN,...,NaN,4,NaN,92.3,NaN,87.0,NaN,5,NaN,3
7,7,Switzerland,73.8,NaN,80.7,NaN,15,NaN,4,NaN,...,NaN,5,NaN,92.6,NaN,86.1,NaN,5,NaN,5
8,8,Japan,73.3,NaN,81.9,NaN,14,NaN,3,NaN,...,NaN,4,NaN,93.8,NaN,86.1,NaN,8,NaN,6
9,9,Netherlands,74.0,NaN,78.7,NaN,13,NaN,4,NaN,...,NaN,5,NaN,90.4,NaN,84.4,NaN,7,NaN,6
10,10,France,72.4,NaN,79.6,NaN,18,NaN,4,NaN,...,NaN,5,NaN,92.2,NaN,82.1,NaN,10,NaN,8
11,11,Finland,70.7,NaN,78.4,NaN,13,NaN,3,NaN,...,NaN,4,NaN,91.8,NaN,81.0,NaN,6,NaN,7
12,12,United States,71.5,NaN,77.4,NaN,20,NaN,6,NaN,...,NaN,7,NaN,87.0,NaN,79.4,NaN,8,NaN,11
13,13,Spain,72.9,NaN,80.0,NaN,27,NaN,4,NaN,...,NaN,5,NaN,93.5,NaN,83.9,NaN,6,NaN,4
14,14,Denmark,73.6,NaN,77.3,NaN,14,NaN,4,NaN,...,NaN,5,NaN,87.4,NaN,81.3,NaN,10,NaN,3
15,15,Austria,70.6,NaN,78.9,NaN,26,NaN,4,NaN,...,NaN,5,NaN,91.9,NaN,82.4,NaN,..,NaN,4
16,16,United Kingdom,72.0,NaN,78.5,NaN,18,NaN,5,NaN,...,NaN,6,NaN,89.6,NaN,83.7,NaN,7,NaN,8
17,17,Belgium,71.6,NaN,78.2,NaN,21,NaN,4,NaN,...,NaN,5,NaN,91.0,NaN,81.9,NaN,..,NaN,8
18,18,Luxembourg,70.6,NaN,78.2,NaN,19,NaN,4,NaN,...,NaN,5,NaN,90.8,NaN,82.4,NaN,0,NaN,12
19,19,New Zealand,71.7,NaN,79.2,NaN,17,NaN,5,NaN,...,NaN,6,NaN,90.0,NaN,84.9,NaN,15,NaN,9
20,20,Italy,72.1,NaN,79.9,NaN,30,NaN,4,NaN,...,NaN,4,NaN,92.5,NaN,84.6,NaN,7,NaN,3
21,21,"Hong Kong, China (SAR)",72.0,NaN,81.5,NaN,..,NaN,..,NaN,...,NaN,..,NaN,93.6,NaN,86.3,NaN,..,NaN,..
22,22,Germany,71.0,NaN,78.7,NaN,22,NaN,4,NaN,...,NaN,5,NaN,91.0,NaN,82.9,NaN,8,NaN,4
23,23,Israel,71.6,NaN,79.7,NaN,24,NaN,5,NaN,...,NaN,6,NaN,92.3,NaN,85.8,NaN,5,NaN,4
24,24,Greece,72.3,NaN,78.3,NaN,38,NaN,4,NaN,...,NaN,5,NaN,91.3,NaN,83.7,NaN,1,NaN,3
25,25,Singapore,69.5,NaN,78.8,NaN,22,NaN,3,NaN,...,NaN,3,NaN,90.8,NaN,84.4,NaN,6,NaN,14
26,26,Korea (Republic of),62.6,NaN,77.0,NaN,43,NaN,5,NaN,...,NaN,5,NaN,90.8,NaN,78.6,NaN,20,NaN,14
27,27,Slovenia,69.8,NaN,76.8,NaN,25,NaN,3,NaN,...,NaN,4,NaN,90.1,NaN,77.6,NaN,17,NaN,6
28,28,Cyprus,71.4,NaN,79.0,NaN,29,NaN,4,NaN,...,NaN,5,NaN,92.3,NaN,86.1,NaN,0,NaN,10
29,29,Portugal,68.0,NaN,77.2,NaN,53,NaN,4,NaN,...,NaN,5,NaN,90.9,NaN,81.0,NaN,8,NaN,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,168,Congo (Democratic Republic of the),46.0,NaN,45.0,NaN,148,NaN,129,NaN,...,NaN,205,NaN,38.8,NaN,33.3,NaN,"1,300",NaN,"1,100"
171,169,Ethiopia,43.5,NaN,50.7,NaN,160,NaN,109,NaN,...,NaN,164,NaN,46.9,NaN,41.4,NaN,870,NaN,720
172,170,Chad,45.6,NaN,50.5,NaN,154,NaN,124,NaN,...,NaN,208,NaN,50.5,NaN,43.7,NaN,"1,100",NaN,"1,500"
173,171,Central African Republic,43.5,NaN,43.3,NaN,145,NaN,115,NaN,...,NaN,193,NaN,32.1,NaN,25.7,NaN,"1,100",NaN,980
174,172,Mozambique,40.3,NaN,44.0,NaN,168,NaN,100,NaN,...,NaN,145,NaN,35.3,NaN,29.2,NaN,410,NaN,520
175,173,Mali,40.0,NaN,51.8,NaN,225,NaN,120,NaN,...,NaN,218,NaN,54.1,NaN,44.3,NaN,580,NaN,970
176,174,Niger,40.5,NaN,54.5,NaN,197,NaN,150,NaN,...,NaN,256,NaN,54.4,NaN,56.8,NaN,590,NaN,"1,800"
177,175,Guinea-Bissau,36.5,NaN,45.5,NaN,..,NaN,124,NaN,...,NaN,200,NaN,40.9,NaN,34.2,NaN,910,NaN,"1,100"
178,176,Burkina Faso,43.6,NaN,50.7,NaN,166,NaN,96,NaN,...,NaN,191,NaN,54.5,NaN,44.0,NaN,480,NaN,700
179,177,Sierra Leone,35.4,NaN,41.0,NaN,206,NaN,165,NaN,...,NaN,282,NaN,37.6,NaN,30.4,NaN,"1,800",NaN,"2,100"
180,Developing countries,NaN,55.8,NaN,65.5,NaN,109,h,57,h,...,h,83,h,70.3,NaN,62.6,NaN,..,NaN,..
181,Least developed countries,NaN,44.6,h,52.7,h,152,h,97,h,...,h,153,h,49.9,h,44.3,h,..,NaN,..
182,Arab States,NaN,51.9,NaN,66.7,NaN,129,NaN,46,NaN,...,NaN,58,NaN,73.5,NaN,66.4,NaN,..,NaN,..
183,East Asia and the Pacific,NaN,60.6,NaN,71.1,NaN,84,NaN,25,NaN,...,NaN,31,NaN,79.6,NaN,71.8,NaN,..,NaN,..
184,Latin America and the Caribbean,NaN,61.2,NaN,72.2,NaN,86,NaN,26,NaN,...,NaN,31,NaN,80.8,NaN,69.3,NaN,..,NaN,..
185,South Asia,NaN,50.3,NaN,62.9,NaN,130,NaN,60,NaN,...,NaN,80,NaN,66.0,NaN,58.4,NaN,..,NaN,..
186,Sub-Saharan Africa,NaN,46.0,NaN,49.1,NaN,144,NaN,102,NaN,...,NaN,172,NaN,43.3,NaN,37.8,NaN,..,NaN,..
187,Central and Eastern Europe and the CIS,NaN,68.7,NaN,68.2,NaN,39,NaN,22,NaN,...,NaN,27,NaN,79.5,NaN,54.9,NaN,..,NaN,..
188,OECD,NaN,70.3,NaN,77.8,NaN,41,NaN,9,NaN,...,NaN,11,NaN,89.2,NaN,80.5,NaN,..,NaN,..
189,High-income OECD,NaN,71.7,NaN,78.9,NaN,22,NaN,5,NaN,...,NaN,6,NaN,90.3,NaN,82.4,NaN,..,NaN,..
190,High human development,NaN,69.4,NaN,75.7,NaN,43,NaN,13,NaN,...,NaN,15,NaN,86.6,NaN,74.8,NaN,..,NaN,..
191,Medium human development,NaN,56.6,NaN,66.9,NaN,106,NaN,45,NaN,...,NaN,59,NaN,72.6,NaN,64.5,NaN,..,NaN,..
192,Low human development,NaN,43.7,NaN,47.9,NaN,155,NaN,108,NaN,...,NaN,184,NaN,42.6,NaN,37.4,NaN,..,NaN,..
193,High income,NaN,71.5,NaN,78.7,NaN,24,NaN,6,NaN,...,NaN,7,NaN,90.2,NaN,82.2,NaN,..,NaN,..
194,Middle income,NaN,61.8,NaN,70.3,NaN,87,NaN,28,NaN,...,NaN,35,NaN,78.9,NaN,68.4,NaN,..,NaN,..
195,Low income,NaN,49.1,NaN,59.2,NaN,130,NaN,75,NaN,...,NaN,113,NaN,60.0,NaN,53.2,NaN,..,NaN,..
196,World,NaN,58.3,h,66.0,h,96,h,52,h,...,h,76,h,72.0,h,63.1,h,..,NaN,..
197,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,a. Data refer to the probability at birth of s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,"SOURCES\nColumns 1, 2, 7 and 8: UN 2007e.\nCol...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#Afficher les 25 dernières lignes afin d'afficher les notes de bas de pages
df.tail(25)

,HDI rank,Country,Life expectancy at birth(years) 1970-1975d,Reference 1,Life expectancy at birth(years) 2000-2005d,Reference 2,"Infant mortality rate(per 1,000 live births) 1970",Reference 3,"Infant mortality rate(per 1,000 live births) 2005",Reference 4,...,Reference 5,"Under-five mortality rate(per 1,000 live births) 2005",Reference 6,Probability at birth of not surviving to age 65a (% of cohort) Female 2000-2005d,Reference 7,Probability at birth of not surviving to age 65a (% of cohort) Male 2000-2005d,Reference 8,"Maternal mortality ratio (per 100,000 live births) Reportedb 1990-2005e",Reference 9,"Maternal mortality ratio (per 100,000 live births) Adjustedc 2005"
175,173,Mali,40.0,NaN,51.8,NaN,225,NaN,120,NaN,...,NaN,218,NaN,54.1,NaN,44.3,NaN,580,NaN,970
176,174,Niger,40.5,NaN,54.5,NaN,197,NaN,150,NaN,...,NaN,256,NaN,54.4,NaN,56.8,NaN,590,NaN,"1,800"
177,175,Guinea-Bissau,36.5,NaN,45.5,NaN,..,NaN,124,NaN,...,NaN,200,NaN,40.9,NaN,34.2,NaN,910,NaN,"1,100"
178,176,Burkina Faso,43.6,NaN,50.7,NaN,166,NaN,96,NaN,...,NaN,191,NaN,54.5,NaN,44.0,NaN,480,NaN,700
179,177,Sierra Leone,35.4,NaN,41.0,NaN,206,NaN,165,NaN,...,NaN,282,NaN,37.6,NaN,30.4,NaN,"1,800",NaN,"2,100"
180,Developing countries,NaN,55.8,NaN,65.5,NaN,109,h,57,h,...,h,83,h,70.3,NaN,62.6,NaN,..,NaN,..
181,Least developed countries,NaN,44.6,h,52.7,h,152,h,97,h,...,h,153,h,49.9,h,44.3,h,..,NaN,..
182,Arab States,NaN,51.9,NaN,66.7,NaN,129,NaN,46,NaN,...,NaN,58,NaN,73.5,NaN,66.4,NaN,..,NaN,..
183,East Asia and the Pacific,NaN,60.6,NaN,71.1,NaN,84,NaN,25,NaN,...,NaN,31,NaN,79.6,NaN,71.8,NaN,..,NaN,..
184,Latin America and the Caribbean,NaN,61.2,NaN,72.2,NaN,86,NaN,26,NaN,...,NaN,31,NaN,80.8,NaN,69.3,NaN,..,NaN,..
185,South Asia,NaN,50.3,NaN,62.9,NaN,130,NaN,60,NaN,...,NaN,80,NaN,66.0,NaN,58.4,NaN,..,NaN,..
186,Sub-Saharan Africa,NaN,46.0,NaN,49.1,NaN,144,NaN,102,NaN,...,NaN,172,NaN,43.3,NaN,37.8,NaN,..,NaN,..
187,Central and Eastern Europe and the CIS,NaN,68.7,NaN,68.2,NaN,39,NaN,22,NaN,...,NaN,27,NaN,79.5,NaN,54.9,NaN,..,NaN,..
188,OECD,NaN,70.3,NaN,77.8,NaN,41,NaN,9,NaN,...,NaN,11,NaN,89.2,NaN,80.5,NaN,..,NaN,..
189,High-income OECD,NaN,71.7,NaN,78.9,NaN,22,NaN,5,NaN,...,NaN,6,NaN,90.3,NaN,82.4,NaN,..,NaN,..
190,High human development,NaN,69.4,NaN,75.7,NaN,43,NaN,13,NaN,...,NaN,15,NaN,86.6,NaN,74.8,NaN,..,NaN,..
191,Medium human development,NaN,56.6,NaN,66.9,NaN,106,NaN,45,NaN,...,NaN,59,NaN,72.6,NaN,64.5,NaN,..,NaN,..
192,Low human development,NaN,43.7,NaN,47.9,NaN,155,NaN,108,NaN,...,NaN,184,NaN,42.6,NaN,37.4,NaN,..,NaN,..
193,High income,NaN,71.5,NaN,78.7,NaN,24,NaN,6,NaN,...,NaN,7,NaN,90.2,NaN,82.2,NaN,..,NaN,..
194,Middle income,NaN,61.8,NaN,70.3,NaN,87,NaN,28,NaN,...,NaN,35,NaN,78.9,NaN,68.4,NaN,..,NaN,..
195,Low income,NaN,49.1,NaN,59.2,NaN,130,NaN,75,NaN,...,NaN,113,NaN,60.0,NaN,53.2,NaN,..,NaN,..
196,World,NaN,58.3,h,66.0,h,96,h,52,h,...,h,76,h,72.0,h,63.1,h,..,NaN,..
197,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,a. Data refer to the probability at birth of s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,"SOURCES\nColumns 1, 2, 7 and 8: UN 2007e.\nCol...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#Sauvegarder les notes,sources et métadonnées dans des dataframes
df_meta = df.iloc[180:197,]
df_notes = df.iloc[197:199,]
df_src = df.iloc[199:200,]


df_meta = df_meta.dropna(how = 'any', axis = 1).reset_index(drop=True)
df_notes = df_notes.dropna(how = 'any', axis = 1).reset_index(drop=True)
df_src = df_src.dropna(how = 'any', axis = 1).reset_index(drop=True)

In [10]:
df_notes

                                            HDI rank
0                                              NOTES
1  a. Data refer to the probability at birth of s...

In [11]:
df_src

                                            HDI rank
0  SOURCES\nColumns 1, 2, 7 and 8: UN 2007e.\nCol...

In [12]:
df_meta

,HDI rank,Life expectancy at birth(years) 1970-1975d,Life expectancy at birth(years) 2000-2005d,"Infant mortality rate(per 1,000 live births) 1970","Infant mortality rate(per 1,000 live births) 2005","Under-five mortality rate(per 1,000 live births) 1970","Under-five mortality rate(per 1,000 live births) 2005",Probability at birth of not surviving to age 65a (% of cohort) Female 2000-2005d,Probability at birth of not surviving to age 65a (% of cohort) Male 2000-2005d,"Maternal mortality ratio (per 100,000 live births) Reportedb 1990-2005e","Maternal mortality ratio (per 100,000 live births) Adjustedc 2005"
0,Developing countries,55.8,65.5,109,57,167,83,70.3,62.6,..,..
1,Least developed countries,44.6,52.7,152,97,245,153,49.9,44.3,..,..
2,Arab States,51.9,66.7,129,46,196,58,73.5,66.4,..,..
3,East Asia and the Pacific,60.6,71.1,84,25,123,31,79.6,71.8,..,..
4,Latin America and the Caribbean,61.2,72.2,86,26,123,31,80.8,69.3,..,..
5,South Asia,50.3,62.9,130,60,206,80,66.0,58.4,..,..
6,Sub-Saharan Africa,46.0,49.1,144,102,244,172,43.3,37.8,..,..
7,Central and Eastern Europe and the CIS,68.7,68.2,39,22,48,27,79.5,54.9,..,..
8,OECD,70.3,77.8,41,9,54,11,89.2,80.5,..,..
9,High-income OECD,71.7,78.9,22,5,28,6,90.3,82.4,..,..
10,High human development,69.4,75.7,43,13,59,15,86.6,74.8,..,..
11,Medium human development,56.6,66.9,106,45,162,59,72.6,64.5,..,..
12,Low human development,43.7,47.9,155,108,264,184,42.6,37.4,..,..
13,High income,71.5,78.7,24,6,32,7,90.2,82.2,..,..
14,Middle income,61.8,70.3,87,28,127,35,78.9,68.4,..,..
15,Low income,49.1,59.2,130,75,209,113,60.0,53.2,..,..
16,World,58.3,66.0,96,52,148,76,72.0,63.1,..,..

In [13]:
# df sans les notes, sources et métadonnées
df = df.drop(np.arange(179,len(df)), axis=0).reset_index(drop=True)
df

,HDI rank,Country,Life expectancy at birth(years) 1970-1975d,Reference 1,Life expectancy at birth(years) 2000-2005d,Reference 2,"Infant mortality rate(per 1,000 live births) 1970",Reference 3,"Infant mortality rate(per 1,000 live births) 2005",Reference 4,...,Reference 5,"Under-five mortality rate(per 1,000 live births) 2005",Reference 6,Probability at birth of not surviving to age 65a (% of cohort) Female 2000-2005d,Reference 7,Probability at birth of not surviving to age 65a (% of cohort) Male 2000-2005d,Reference 8,"Maternal mortality ratio (per 100,000 live births) Reportedb 1990-2005e",Reference 9,"Maternal mortality ratio (per 100,000 live births) Adjustedc 2005"
0,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Iceland,74.3,NaN,81.0,NaN,13,NaN,2,NaN,...,NaN,3,NaN,92.4,NaN,88.7,NaN,..,NaN,4
2,2,Norway,74.4,NaN,79.3,NaN,13,NaN,3,NaN,...,NaN,4,NaN,91.7,NaN,85.1,NaN,6,NaN,7
3,3,Australia,71.7,NaN,80.4,NaN,17,NaN,5,NaN,...,NaN,6,NaN,92.2,NaN,86.2,NaN,..,NaN,4
4,4,Canada,73.2,NaN,79.8,NaN,19,NaN,5,NaN,...,NaN,6,NaN,91.0,NaN,84.9,NaN,..,NaN,7
5,5,Ireland,71.3,NaN,77.8,NaN,20,NaN,5,NaN,...,NaN,6,NaN,90.0,NaN,83.2,NaN,6,NaN,1
6,6,Sweden,74.7,NaN,80.1,NaN,11,NaN,3,NaN,...,NaN,4,NaN,92.3,NaN,87.0,NaN,5,NaN,3
7,7,Switzerland,73.8,NaN,80.7,NaN,15,NaN,4,NaN,...,NaN,5,NaN,92.6,NaN,86.1,NaN,5,NaN,5
8,8,Japan,73.3,NaN,81.9,NaN,14,NaN,3,NaN,...,NaN,4,NaN,93.8,NaN,86.1,NaN,8,NaN,6
9,9,Netherlands,74.0,NaN,78.7,NaN,13,NaN,4,NaN,...,NaN,5,NaN,90.4,NaN,84.4,NaN,7,NaN,6
10,10,France,72.4,NaN,79.6,NaN,18,NaN,4,NaN,...,NaN,5,NaN,92.2,NaN,82.1,NaN,10,NaN,8
11,11,Finland,70.7,NaN,78.4,NaN,13,NaN,3,NaN,...,NaN,4,NaN,91.8,NaN,81.0,NaN,6,NaN,7
12,12,United States,71.5,NaN,77.4,NaN,20,NaN,6,NaN,...,NaN,7,NaN,87.0,NaN,79.4,NaN,8,NaN,11
13,13,Spain,72.9,NaN,80.0,NaN,27,NaN,4,NaN,...,NaN,5,NaN,93.5,NaN,83.9,NaN,6,NaN,4
14,14,Denmark,73.6,NaN,77.3,NaN,14,NaN,4,NaN,...,NaN,5,NaN,87.4,NaN,81.3,NaN,10,NaN,3
15,15,Austria,70.6,NaN,78.9,NaN,26,NaN,4,NaN,...,NaN,5,NaN,91.9,NaN,82.4,NaN,..,NaN,4
16,16,United Kingdom,72.0,NaN,78.5,NaN,18,NaN,5,NaN,...,NaN,6,NaN,89.6,NaN,83.7,NaN,7,NaN,8
17,17,Belgium,71.6,NaN,78.2,NaN,21,NaN,4,NaN,...,NaN,5,NaN,91.0,NaN,81.9,NaN,..,NaN,8
18,18,Luxembourg,70.6,NaN,78.2,NaN,19,NaN,4,NaN,...,NaN,5,NaN,90.8,NaN,82.4,NaN,0,NaN,12
19,19,New Zealand,71.7,NaN,79.2,NaN,17,NaN,5,NaN,...,NaN,6,NaN,90.0,NaN,84.9,NaN,15,NaN,9
20,20,Italy,72.1,NaN,79.9,NaN,30,NaN,4,NaN,...,NaN,4,NaN,92.5,NaN,84.6,NaN,7,NaN,3
21,21,"Hong Kong, China (SAR)",72.0,NaN,81.5,NaN,..,NaN,..,NaN,...,NaN,..,NaN,93.6,NaN,86.3,NaN,..,NaN,..
22,22,Germany,71.0,NaN,78.7,NaN,22,NaN,4,NaN,...,NaN,5,NaN,91.0,NaN,82.9,NaN,8,NaN,4
23,23,Israel,71.6,NaN,79.7,NaN,24,NaN,5,NaN,...,NaN,6,NaN,92.3,NaN,85.8,NaN,5,NaN,4
24,24,Greece,72.3,NaN,78.3,NaN,38,NaN,4,NaN,...,NaN,5,NaN,91.3,NaN,83.7,NaN,1,NaN,3
25,25,Singapore,69.5,NaN,78.8,NaN,22,NaN,3,NaN,...,NaN,3,NaN,90.8,NaN,84.4,NaN,6,NaN,14
26,26,Korea (Republic of),62.6,NaN,77.0,NaN,43,NaN,5,NaN,...,NaN,5,NaN,90.8,NaN,78.6,NaN,20,NaN,14
27,27,Slovenia,69.8,NaN,76.8,NaN,25,NaN,3,NaN,...,NaN,4,NaN,90.1,NaN,77.6,NaN,17,NaN,6
28,28,Cyprus,71.4,NaN,79.0,NaN,29,NaN,4,NaN,...,NaN,5,NaN,92.3,NaN,86.1,NaN,0,NaN,10
29,29,Portugal,68.0,NaN,77.2,NaN,53,NaN,4,NaN,...,NaN,5,NaN,90.9,NaN,81.0,NaN,8,NaN,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,148,Kenya,53.6,NaN,51.0,NaN,96,NaN,79,NaN,...,NaN,120,NaN,42.5,NaN,37.0,NaN,410,NaN,560
150,149,Djibouti,44.4,NaN,53.4,NaN,..,NaN,88,NaN,...,NaN,133,NaN,50.4,NaN,43.7,NaN,74,NaN,650
151,150,Timor-Leste,40.0,NaN,58.3,NaN,..,NaN,52,NaN,...,NaN,61,NaN,57.3,NaN,52.9,NaN,..,NaN,380
152,151,Zimbabwe,55.6,NaN,40.0,NaN,86,NaN,81,NaN,...,NaN,132,NaN,18.0,NaN,15.0,NaN,"1,100",NaN,880
153,152,Togo,49.8,NaN,57.6,NaN,128,NaN,78,NaN,...,NaN,139,NaN,61.2,NaN,52.8,NaN,480,NaN,510
154,153,Yemen,39.8,NaN,60.3,NaN,202,NaN,76,NaN,...,NaN,102,NaN,61.7,NaN,55.0,NaN,370,NaN,430
155,154,Uganda,51.0,NaN,47.8,NaN,100,NaN,79,NaN,...,NaN,136,NaN,36.6,NaN,33.6,NaN,510,NaN,550
156,155,Gambia,38.3,NaN,58.0,NaN,180,NaN,97,NaN,...,NaN,137,NaN,61.4,NaN,54.8,NaN,730,NaN,690
157,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,156,Senegal,45.8,NaN,61.6,NaN,164,NaN,77,NaN,...,NaN,136,NaN,69.7,NaN,60.7,NaN,430,NaN,980
159,157,Eritrea,44.1,NaN,55.2,NaN,143,NaN,50,NaN,...,NaN,78,NaN,50.2,NaN,36.4,NaN,"1,000",NaN,450
160,158,Nigeria,42.8,NaN,46.6,NaN,140,NaN,100,NaN,...,NaN,194,NaN,40.6,NaN,37.0,NaN,..,NaN,"1,100"
161,159,Tanzania (United Republic of),47.6,NaN,49.7,NaN,129,NaN,76,NaN,...,NaN,122,NaN,41.0,NaN,36.0,NaN,580,NaN,950
162,160,Guinea,38.8,NaN,53.7,NaN,197,NaN,98,NaN,...,NaN,150,NaN,55.7,NaN,48.9,NaN,530,NaN,910
163,161,Rwanda,44.6,NaN,43.4,NaN,124,NaN,118,NaN,...,NaN,203,NaN,34.5,NaN,28.3,NaN,"1,100",NaN,"1,300"
164,162,Angola,37.9,NaN,41.0,NaN,180,NaN,154,NaN,...,NaN,260,NaN,33.9,NaN,27.5,NaN,..,NaN,"1,400"
165,163,Benin,47.0,NaN,54.4,NaN,149,NaN,89,NaN,...,NaN,150,NaN,55.7,NaN,48.6,NaN,500,NaN,840
166,164,Malawi,41.8,NaN,45.0,NaN,204,NaN,79,NaN,...,NaN,125,NaN,33.7,NaN,27.4,NaN,980,NaN,"1,100"
167,165,Zambia,50.1,NaN,39.2,NaN,109,NaN,102,NaN,...,NaN,182,NaN,21.9,NaN,18.6,NaN,730,NaN,830
168,166,Côte d'Ivoire,49.8,NaN,46.8,NaN,158,NaN,118,NaN,...,NaN,195,NaN,40.7,NaN,34.9,NaN,600,NaN,810
169,167,Burundi,44.1,NaN,47.4,NaN,138,NaN,114,NaN,...,NaN,190,NaN,41.1,NaN,35.9,NaN,..,NaN,"1,100"
170,168,Congo (Democratic Republic of the),46.0,NaN,45.0,NaN,148,NaN,129,NaN,...,NaN,205,NaN,38.8,NaN,33.3,NaN,"1,300",NaN,"1,100"
171,169,Ethiopia,43.5,NaN,50.7,NaN,160,NaN,109,NaN,...,NaN,164,NaN,46.9,NaN,41.4,NaN,870,NaN,720
172,170,Chad,45.6,NaN,50.5,NaN,154,NaN,124,NaN,...,NaN,208,NaN,50.5,NaN,43.7,NaN,"1,100",NaN,"1,500"
173,171,Central African Republic,43.5,NaN,43.3,NaN,145,NaN,115,NaN,...,NaN,193,NaN,32.1,NaN,25.7,NaN,"1,100",NaN,980
174,172,Mozambique,40.3,NaN,44.0,NaN,168,NaN,100,NaN,...,NaN,145,NaN,35.3,NaN,29.2,NaN,410,NaN,520
175,173,Mali,40.0,NaN,51.8,NaN,225,NaN,120,NaN,...,NaN,218,NaN,54.1,NaN,44.3,NaN,580,NaN,970
176,174,Niger,40.5,NaN,54.5,NaN,197,NaN,150,NaN,...,NaN,256,NaN,54.4,NaN,56.8,NaN,590,NaN,"1,800"
177,175,Guinea-Bissau,36.5,NaN,45.5,NaN,..,NaN,124,NaN,...,NaN,200,NaN,40.9,NaN,34.2,NaN,910,NaN,"1,100"
178,176,Burkina Faso,43.6,NaN,50.7,NaN,166,NaN,96,NaN,...,NaN,191,NaN,54.5,NaN,44.0,NaN,480,NaN,700

In [14]:
hdi_categories = ["HIGH HUMAN DEVELOPMENT", "MEDIUM HUMAN DEVELOPMENT", "LOW HUMAN DEVELOPMENT"]

# Se débarrasser des rangées avec les catégories HDI
df = df.drop(df[df["HDI rank"].isin(hdi_categories)].index, axis=0).reset_index(drop=True)

# Référence pour np.where https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html
# Pensez que cela ressemble à une déclaration du type "if" : where(test est vrai, vrai-quelque chose, faux-quelque chose)
# ceci peut aussi être imbriqué : where(test is true, true-thing, where(new-test is true, true-thing, false-thing))
# Classification des Pays selon le niveau de developpement HDI rank 
df.loc[:, "HDI category"] = np.where(df["HDI rank"] > 155,
                                     "LOW HUMAN DEVELOPMENT",
                                     np.where(df["HDI rank"] > 70,
                                              "MEDIUM HUMAN DEVELOPMENT",
                                              "HIGH HUMAN DEVELOPMENT"
                                             )
                                    )
df.sort_values(by="HDI rank", inplace=True)
df

,HDI rank,Country,Life expectancy at birth(years) 1970-1975d,Reference 1,Life expectancy at birth(years) 2000-2005d,Reference 2,"Infant mortality rate(per 1,000 live births) 1970",Reference 3,"Infant mortality rate(per 1,000 live births) 2005",Reference 4,...,"Under-five mortality rate(per 1,000 live births) 2005",Reference 6,Probability at birth of not surviving to age 65a (% of cohort) Female 2000-2005d,Reference 7,Probability at birth of not surviving to age 65a (% of cohort) Male 2000-2005d,Reference 8,"Maternal mortality ratio (per 100,000 live births) Reportedb 1990-2005e",Reference 9,"Maternal mortality ratio (per 100,000 live births) Adjustedc 2005",HDI category
0,1,Iceland,74.3,NaN,81.0,NaN,13,NaN,2,NaN,...,3,NaN,92.4,NaN,88.7,NaN,..,NaN,4,HIGH HUMAN DEVELOPMENT
1,2,Norway,74.4,NaN,79.3,NaN,13,NaN,3,NaN,...,4,NaN,91.7,NaN,85.1,NaN,6,NaN,7,HIGH HUMAN DEVELOPMENT
2,3,Australia,71.7,NaN,80.4,NaN,17,NaN,5,NaN,...,6,NaN,92.2,NaN,86.2,NaN,..,NaN,4,HIGH HUMAN DEVELOPMENT
3,4,Canada,73.2,NaN,79.8,NaN,19,NaN,5,NaN,...,6,NaN,91.0,NaN,84.9,NaN,..,NaN,7,HIGH HUMAN DEVELOPMENT
4,5,Ireland,71.3,NaN,77.8,NaN,20,NaN,5,NaN,...,6,NaN,90.0,NaN,83.2,NaN,6,NaN,1,HIGH HUMAN DEVELOPMENT
5,6,Sweden,74.7,NaN,80.1,NaN,11,NaN,3,NaN,...,4,NaN,92.3,NaN,87.0,NaN,5,NaN,3,HIGH HUMAN DEVELOPMENT
6,7,Switzerland,73.8,NaN,80.7,NaN,15,NaN,4,NaN,...,5,NaN,92.6,NaN,86.1,NaN,5,NaN,5,HIGH HUMAN DEVELOPMENT
7,8,Japan,73.3,NaN,81.9,NaN,14,NaN,3,NaN,...,4,NaN,93.8,NaN,86.1,NaN,8,NaN,6,HIGH HUMAN DEVELOPMENT
8,9,Netherlands,74.0,NaN,78.7,NaN,13,NaN,4,NaN,...,5,NaN,90.4,NaN,84.4,NaN,7,NaN,6,HIGH HUMAN DEVELOPMENT
9,10,France,72.4,NaN,79.6,NaN,18,NaN,4,NaN,...,5,NaN,92.2,NaN,82.1,NaN,10,NaN,8,HIGH HUMAN DEVELOPMENT
10,11,Finland,70.7,NaN,78.4,NaN,13,NaN,3,NaN,...,4,NaN,91.8,NaN,81.0,NaN,6,NaN,7,HIGH HUMAN DEVELOPMENT
11,12,United States,71.5,NaN,77.4,NaN,20,NaN,6,NaN,...,7,NaN,87.0,NaN,79.4,NaN,8,NaN,11,HIGH HUMAN DEVELOPMENT
12,13,Spain,72.9,NaN,80.0,NaN,27,NaN,4,NaN,...,5,NaN,93.5,NaN,83.9,NaN,6,NaN,4,HIGH HUMAN DEVELOPMENT
13,14,Denmark,73.6,NaN,77.3,NaN,14,NaN,4,NaN,...,5,NaN,87.4,NaN,81.3,NaN,10,NaN,3,HIGH HUMAN DEVELOPMENT
14,15,Austria,70.6,NaN,78.9,NaN,26,NaN,4,NaN,...,5,NaN,91.9,NaN,82.4,NaN,..,NaN,4,HIGH HUMAN DEVELOPMENT
15,16,United Kingdom,72.0,NaN,78.5,NaN,18,NaN,5,NaN,...,6,NaN,89.6,NaN,83.7,NaN,7,NaN,8,HIGH HUMAN DEVELOPMENT
16,17,Belgium,71.6,NaN,78.2,NaN,21,NaN,4,NaN,...,5,NaN,91.0,NaN,81.9,NaN,..,NaN,8,HIGH HUMAN DEVELOPMENT
17,18,Luxembourg,70.6,NaN,78.2,NaN,19,NaN,4,NaN,...,5,NaN,90.8,NaN,82.4,NaN,0,NaN,12,HIGH HUMAN DEVELOPMENT
18,19,New Zealand,71.7,NaN,79.2,NaN,17,NaN,5,NaN,...,6,NaN,90.0,NaN,84.9,NaN,15,NaN,9,HIGH HUMAN DEVELOPMENT
19,20,Italy,72.1,NaN,79.9,NaN,30,NaN,4,NaN,...,4,NaN,92.5,NaN,84.6,NaN,7,NaN,3,HIGH HUMAN DEVELOPMENT
20,21,"Hong Kong, China (SAR)",72.0,NaN,81.5,NaN,..,NaN,..,NaN,...,..,NaN,93.6,NaN,86.3,NaN,..,NaN,..,HIGH HUMAN DEVELOPMENT
21,22,Germany,71.0,NaN,78.7,NaN,22,NaN,4,NaN,...,5,NaN,91.0,NaN,82.9,NaN,8,NaN,4,HIGH HUMAN DEVELOPMENT
22,23,Israel,71.6,NaN,79.7,NaN,24,NaN,5,NaN,...,6,NaN,92.3,NaN,85.8,NaN,5,NaN,4,HIGH HUMAN DEVELOPMENT
23,24,Greece,72.3,NaN,78.3,NaN,38,NaN,4,NaN,...,5,NaN,91.3,NaN,83.7,NaN,1,NaN,3,HIGH HUMAN DEVELOPMENT
24,25,Singapore,69.5,NaN,78.8,NaN,22,NaN,3,NaN,...,3,NaN,90.8,NaN,84.4,NaN,6,NaN,14,HIGH HUMAN DEVELOPMENT
25,26,Korea (Republic of),62.6,NaN,77.0,NaN,43,NaN,5,NaN,...,5,NaN,90.8,NaN,78.6,NaN,20,NaN,14,HIGH HUMAN DEVELOPMENT
26,27,Slovenia,69.8,NaN,76.8,NaN,25,NaN,3,NaN,...,4,NaN,90.1,NaN,77.6,NaN,17,NaN,6,HIGH HUMAN DEVELOPMENT
27,28,Cyprus,71.4,NaN,79.0,NaN,29,NaN,4,NaN,...,5,NaN,92.3,NaN,86.1,NaN,0,NaN,10,HIGH HUMAN DEVELOPMENT
28,29,Portugal,68.0,NaN,77.2,NaN,53,NaN,4,NaN,...,5,NaN,90.9,NaN,81.0,NaN,8,NaN,11,HIGH HUMAN DEVELOPMENT
29,30,Brunei Darussalam,68.3,NaN,76.3,NaN,58,NaN,8,NaN,...,9,NaN,87.7,NaN,84.5,NaN,0,NaN,41,HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,Sudan,45.1,NaN,56.4,NaN,104,NaN,62,NaN,...,90,NaN,55.3,NaN,49.7,NaN,550,g,450,MEDIUM HUMAN DEVELOPMENT
147,148,Kenya,53.6,NaN,51.0,NaN,96,NaN,79,NaN,...,120,NaN,42.5,NaN,37.0,NaN,410,NaN,560,MEDIUM HUMAN DEVELOPMENT
148,149,Djibouti,44.4,NaN,53.4,NaN,..,NaN,88,NaN,...,133,NaN,50.4,NaN,43.7,NaN,74,NaN,650,MEDIUM HUMAN DEVELOPMENT
149,150,Timor-Leste,40.0,NaN,58.3,NaN,..,NaN,52,NaN,...,61,NaN,57.3,NaN,52.9,NaN,..,NaN,380,MEDIUM HUMAN DEVELOPMENT
150,151,Zimbabwe,55.6,NaN,40.0,NaN,86,NaN,81,NaN,...,132,NaN,18.0,NaN,15.0,NaN,"1,100",NaN,880,MEDIUM HUMAN DEVELOPMENT
151,152,Togo,49.8,NaN,57.6,NaN,128,NaN,78,NaN,...,139,NaN,61.2,NaN,52.8,NaN,480,NaN,510,MEDIUM HUMAN DEVELOPMENT
152,153,Yemen,39.8,NaN,60.3,NaN,202,NaN,76,NaN,...,102,NaN,61.7,NaN,55.0,NaN,370,NaN,430,MEDIUM HUMAN DEVELOPMENT
153,154,Uganda,51.0,NaN,47.8,NaN,100,NaN,79,NaN,...,136,NaN,36.6,NaN,33.6,NaN,510,NaN,550,MEDIUM HUMAN DEVELOPMENT
154,155,Gambia,38.3,NaN,58.0,NaN,180,NaN,97,NaN,...,137,NaN,61.4,NaN,54.8,NaN,730,NaN,690,MEDIUM HUMAN DEVELOPMENT
155,156,Senegal,45.8,NaN,61.6,NaN,164,NaN,77,NaN,...,136,NaN,69.7,NaN,60.7,NaN,430,NaN,980,LOW HUMAN DEVELOPMENT
156,157,Eritrea,44.1,NaN,55.2,NaN,143,NaN,50,NaN,...,78,NaN,50.2,NaN,36.4,NaN,"1,000",NaN,450,LOW HUMAN DEVELOPMENT
157,158,Nigeria,42.8,NaN,46.6,NaN,140,NaN,100,NaN,...,194,NaN,40.6,NaN,37.0,NaN,..,NaN,"1,100",LOW HUMAN DEVELOPMENT
158,159,Tanzania (United Republic of),47.6,NaN,49.7,NaN,129,NaN,76,NaN,...,122,NaN,41.0,NaN,36.0,NaN,580,NaN,950,LOW HUMAN DEVELOPMENT
159,160,Guinea,38.8,NaN,53.7,NaN,197,NaN,98,NaN,...,150,NaN,55.7,NaN,48.9,NaN,530,NaN,910,LOW HUMAN DEVELOPMENT
160,161,Rwanda,44.6,NaN,43.4,NaN,124,NaN,118,NaN,...,203,NaN,34.5,NaN,28.3,NaN,"1,100",NaN,"1,300",LOW HUMAN DEVELOPMENT
161,162,Angola,37.9,NaN,41.0,NaN,180,NaN,154,NaN,...,260,NaN,33.9,NaN,27.5,NaN,..,NaN,"1,400",LOW HUMAN DEVELOPMENT
162,163,Benin,47.0,NaN,54.4,NaN,149,NaN,89,NaN,...,150,NaN,55.7,NaN,48.6,NaN,500,NaN,840,LOW HUMAN DEVELOPMENT
163,164,Malawi,41.8,NaN,45.0,NaN,204,NaN,79,NaN,...,125,NaN,33.7,NaN,27.4,NaN,980,NaN,"1,100",LOW HUMAN DEVELOPMENT
164,165,Zambia,50.1,NaN,39.2,NaN,109,NaN,102,NaN,...,182,NaN,21.9,NaN,18.6,NaN,730,NaN,830,LOW HUMAN DEVELOPMENT
165,166,Côte d'Ivoire,49.8,NaN,46.8,NaN,158,NaN,118,NaN,...,195,NaN,40.7,NaN,34.9,NaN,600,NaN,810,LOW HUMAN DEVELOPMENT
166,167,Burundi,44.1,NaN,47.4,NaN,138,NaN,114,NaN,...,190,NaN,41.1,NaN,35.9,NaN,..,NaN,"1,100",LOW HUMAN DEVELOPMENT
167,168,Congo (Democratic Republic of the),46.0,NaN,45.0,NaN,148,NaN,129,NaN,...,205,NaN,38.8,NaN,33.3,NaN,"1,300",NaN,"1,100",LOW HUMAN DEVELOPMENT
168,169,Ethiopia,43.5,NaN,50.7,NaN,160,NaN,109,NaN,...,164,NaN,46.9,NaN,41.4,NaN,870,NaN,720,LOW HUMAN DEVELOPMENT
169,170,Chad,45.6,NaN,50.5,NaN,154,NaN,124,NaN,...,208,NaN,50.5,NaN,43.7,NaN,"1,100",NaN,"1,500",LOW HUMAN DEVELOPMENT
170,171,Central African Republic,43.5,NaN,43.3,NaN,145,NaN,115,NaN,...,193,NaN,32.1,NaN,25.7,NaN,"1,100",NaN,980,LOW HUMAN DEVELOPMENT
171,172,Mozambique,40.3,NaN,44.0,NaN,168,NaN,100,NaN,...,145,NaN,35.3,NaN,29.2,NaN,410,NaN,520,LOW HUMAN DEVELOPMENT
172,173,Mali,40.0,NaN,51.8,NaN,225,NaN,120,NaN,...,218,NaN,54.1,NaN,44.3,NaN,580,NaN,970,LOW HUMAN DEVELOPMENT
173,174,Niger,40.5,NaN,54.5,NaN,197,NaN,150,NaN,...,256,NaN,54.4,NaN,56.8,NaN,590,NaN,"1,800",LOW HUMAN DEVELOPMENT
174,175,Guinea-Bissau,36.5,NaN,45.5,NaN,..,NaN,124,NaN,...,200,NaN,40.9,NaN,34.2,NaN,910,NaN,"1,100",LOW HUMAN DEVELOPMENT
175,176,Burkina Faso,43.6,NaN,50.7,NaN,166,NaN,96,NaN,...,191,NaN,54.5,NaN,44.0,NaN,480,NaN,700,LOW HUMAN DEVELOPMENT

In [15]:
#Enregistrons nos données

with pd.ExcelWriter('HDR 2007-2008 Table 10.xlsx') as writer:
    df.to_excel(writer, sheet_name = 'Table_10', index = False)
    df_notes.to_excel(writer, sheet_name = 'NOTES', index = False)
    df_src.to_excel(writer, sheet_name = 'SOURCES', index = False)
    df_meta.to_excel(writer, sheet_name = 'METADONNEES', index = False)